修正中英文不匹配的问题
WForst-Breeze/WForst-Breeze pull request #9
Opened 2024-08-06 11:58 UTC by Deep-Dark-Forest

2024-08-06 12:02 UTC, hejiehao commented on README.md
> +- [ ] Hey there! I am WForst Breeze, you can simply call me SC or WFB, or whatever you like!I am a student taking the university entrance examination in 2025, and I may not have enough time now. I'll
```suggestion
- [ ] Hey there! I am WForst Breeze, you can simply call me SC or WFB, or whatever you like! I am a student who is going to take the University Entrance Examination in 2025, and I may not have enough time now. I'll do my best to help with any questions!
```

2024-08-06 12:16 UTC, wuliaodexiaoluo requested changes

2024-08-06 12:16 UTC, wuliaodexiaoluo commented on README.md
> +- [ ] Hey there! I am WForst Breeze, you can simply call me SC or WFB, or whatever you like! I am a student who is going to take the University Entrance Examination in 2025, and I may not have enough
给我嫖个  CO-Author

2024-08-06 12:17 UTC, wuliaodexiaoluo commented on README.md
> +- [ ] Hey there! I am WForst Breeze, you can simply call me SC or WFB, or whatever you like! I am a student who is going to take the University Entrance Examination in 2025, and I may not have enough
``

2024-08-06 12:19 UTC, wuliaodexiaoluo requested changes

2024-08-06 12:19 UTC, wuliaodexiaoluo commented on README.md
> +- [ ] Hey there! I am WForst Breeze, you can simply call me SC or WFB, or whatever you like! I am a student who is going to take the University Entrance Examination in 2025, and I may not have enough
```suggestion
- [ ] Hey there! I am WForst Breeze, you can simply call me SC or WFB, or whatever you like! I am a student who is going to take the University Entrance Examination in 2025, and I may not have enough time now. I'll do my best to help with any questions! 
```

2024-08-06 12:19 UTC, wuliaodexiaoluo commented on README.md
> +- [ ] Hey there! I am WForst Breeze, you can simply call me SC or WFB, or whatever you like! I am a student who is going to take the University Entrance Examination in 2025, and I may not have enough
给我整 CO-Author
不然我掐死你！（超凶


（bushi

2024-08-06 12:19 UTC, WForst-Breeze reviewed
非常好 PR，使我大脑旋转 :))))

2024-08-06 12:27 UTC, hejiehao commented
OK 了，也是做了个大项目

2024-08-06 14:11 UTC, Deep-Dark-Forest commented on README.md
> +- [ ] Hey there! I am WForst Breeze, you can simply call me SC or WFB, or whatever you like! I am a student who is going to take the University Entrance Examination in 2025, and I may not have enough
nope

2024-08-14 14:44 UTC, Deep-Dark-Forest commented
~~要不等 WFB 高考完了再合并~~

2024-08-30 08:23 UTC, wuliaodexiaoluo commented
前来考古(bushi

2024-10-03 10:52 UTC, WForst-Breeze commented
> ~~要不等 WFB 高考完了再合并~~

好主意

2024-10-04 09:29 UTC, closed without merging